from . import noc_ticket
from . import res_partner
from . import noc_report_wizard
from . import noc_report_history
from . import whatsapp_settings
from . import whatsapp_template
from . import noc_event
from . import noc_incident
from . import noc_whatsapp_session
from . import noc_zone
from . import noc_action_request
from . import noc_device